using Microsoft.Data.Sqlite;

namespace QueryLens.Core;

public sealed class LocalStore : IAsyncDisposable
{
    readonly SqliteConnection _connection;
    public LocalStore(string path) { _connection = new SqliteConnection($"Data Source={path};Pooling=False"); }
    public async Task InitializeAsync(CancellationToken ct = default) { await _connection.OpenAsync(ct); using var c = _connection.CreateCommand(); c.CommandText = "CREATE TABLE IF NOT EXISTS connections(id TEXT PRIMARY KEY,name TEXT NOT NULL,dialect TEXT NOT NULL,host TEXT,port INTEGER,database_name TEXT,auth TEXT,use_tls INTEGER,timeout_seconds INTEGER,user_name TEXT,secret_ref TEXT); CREATE TABLE IF NOT EXISTS slow_queries(id TEXT PRIMARY KEY,connection_id TEXT,raw_sql TEXT,redacted_sql TEXT,normalized_sql TEXT,fingerprint TEXT,observed_at TEXT,calls INTEGER,total_ms REAL,min_ms REAL,max_ms REAL,rows_count INTEGER,native_id TEXT,is_offline INTEGER); CREATE TABLE IF NOT EXISTS plans(id TEXT PRIMARY KEY,connection_id TEXT,dialect TEXT,version TEXT,method TEXT,collected_at TEXT,raw_text TEXT,is_baseline INTEGER,fingerprint TEXT,is_offline INTEGER);"; await c.ExecuteNonQueryAsync(ct); await _connection.CloseAsync(); }
    async Task Open(CancellationToken ct) { if (_connection.State != System.Data.ConnectionState.Open) await _connection.OpenAsync(ct); }
    public async Task SaveConnectionAsync(ConnectionProfile p, CancellationToken ct = default) { await Open(ct); using var c = _connection.CreateCommand(); c.CommandText = "INSERT OR REPLACE INTO connections VALUES($id,$name,$dialect,$host,$port,$db,$auth,$tls,$timeout,$user,$secret)"; Add(c,"id",p.Id); Add(c,"name",p.Name); Add(c,"dialect",p.Dialect); Add(c,"host",p.Host); Add(c,"port",p.Port); Add(c,"db",p.Database); Add(c,"auth",p.Authentication); Add(c,"tls",p.UseTls?1:0); Add(c,"timeout",p.TimeoutSeconds); Add(c,"user",p.UserName); Add(c,"secret",p.SecretReference is null ? null : Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(p.SecretReference))); await c.ExecuteNonQueryAsync(ct); await _connection.CloseAsync(); }
    public async Task<IReadOnlyList<ConnectionProfile>> GetConnectionsAsync(CancellationToken ct = default) { await Open(ct); var list=new List<ConnectionProfile>(); using var c=_connection.CreateCommand(); c.CommandText="SELECT * FROM connections"; using var r=await c.ExecuteReaderAsync(ct); while(await r.ReadAsync(ct)) { string? secret = r.IsDBNull(10)?null:r.GetString(10); if(secret is not null) { try { secret=System.Text.Encoding.UTF8.GetString(Convert.FromBase64String(secret)); } catch(FormatException) { } } list.Add(new(Guid.Parse(r.GetString(0)),r.GetString(1),Enum.Parse<DatabaseDialect>(r.GetString(2)),r.IsDBNull(3)?"":r.GetString(3),r.IsDBNull(4)?0:r.GetInt32(4),r.IsDBNull(5)?"":r.GetString(5),Enum.Parse<AuthenticationMode>(r.GetString(6)),r.GetInt32(7)!=0,r.GetInt32(8),r.IsDBNull(9)?null:r.GetString(9),secret)); } await _connection.CloseAsync(); return list; }
    public async Task SaveSlowQueryAsync(SlowQuery q, CancellationToken ct = default) { await Open(ct); using var c=_connection.CreateCommand(); c.CommandText="INSERT OR REPLACE INTO slow_queries VALUES($id,$cid,$raw,$red,$norm,$fp,$at,$calls,$total,$min,$max,$rows,$native,$offline)"; Add(c,"id",q.Id); Add(c,"cid",q.ConnectionId); Add(c,"raw",q.RawSql); Add(c,"red",q.RedactedSql); Add(c,"norm",q.NormalizedSql); Add(c,"fp",q.Fingerprint); Add(c,"at",q.ObservedAt.ToString("O")); Add(c,"calls",q.Calls); Add(c,"total",q.TotalDuration?.TotalMilliseconds); Add(c,"min",q.MinDuration?.TotalMilliseconds); Add(c,"max",q.MaxDuration?.TotalMilliseconds); Add(c,"rows",q.Rows); Add(c,"native",q.NativeQueryId); Add(c,"offline",q.IsOfflineSample?1:0); await c.ExecuteNonQueryAsync(ct); await _connection.CloseAsync(); }
    public async Task SavePlanAsync(ExecutionPlan p, CancellationToken ct = default) { await Open(ct); using var c=_connection.CreateCommand(); c.CommandText="INSERT OR REPLACE INTO plans VALUES($id,$cid,$dialect,$version,$method,$at,$raw,$base,$fp,$offline)"; Add(c,"id",p.Id); Add(c,"cid",p.ConnectionId); Add(c,"dialect",p.Dialect); Add(c,"version",p.SourceVersion); Add(c,"method",p.CollectionMethod); Add(c,"at",p.CollectedAt.ToString("O")); Add(c,"raw",p.RawText); Add(c,"base",p.IsBaseline?1:0); Add(c,"fp",p.QueryFingerprint); Add(c,"offline",p.IsOfflineSample?1:0); await c.ExecuteNonQueryAsync(ct); await _connection.CloseAsync(); }
    public async Task DeleteConnectionAsync(Guid id, CancellationToken ct = default) { await Open(ct); using var c=_connection.CreateCommand(); c.CommandText="DELETE FROM connections WHERE id=$id"; Add(c,"id",id); await c.ExecuteNonQueryAsync(ct); await _connection.CloseAsync(); }
    public async Task<IReadOnlyList<SlowQuery>> GetSlowQueriesAsync(Guid? connectionId = null, int limit = 500, CancellationToken ct = default) { await Open(ct); var list=new List<SlowQuery>(); using var c=_connection.CreateCommand(); c.CommandText="SELECT id,connection_id,raw_sql,redacted_sql,normalized_sql,fingerprint,observed_at,calls,total_ms,min_ms,max_ms,rows_count,native_id,is_offline FROM slow_queries WHERE ($cid IS NULL OR connection_id=$cid) ORDER BY observed_at DESC LIMIT $limit"; Add(c,"cid",connectionId); Add(c,"limit",Math.Clamp(limit,1,10000)); using var r=await c.ExecuteReaderAsync(ct); while(await r.ReadAsync(ct)) list.Add(new(Guid.Parse(r.GetString(0)),r.IsDBNull(1)?null:Guid.Parse(r.GetString(1)),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),DateTimeOffset.Parse(r.GetString(6)),r.GetInt64(7),r.IsDBNull(8)?null:TimeSpan.FromMilliseconds(r.GetDouble(8)),r.IsDBNull(9)?null:TimeSpan.FromMilliseconds(r.GetDouble(9)),r.IsDBNull(10)?null:TimeSpan.FromMilliseconds(r.GetDouble(10)),r.IsDBNull(11)?null:r.GetInt64(11),r.IsDBNull(12)?null:r.GetString(12),null,r.GetInt32(13)!=0)); await _connection.CloseAsync(); return list; }    static void Add(SqliteCommand c,string n,object? v)=>c.Parameters.AddWithValue("$"+n,v??DBNull.Value);
    public ValueTask DisposeAsync()=>_connection.DisposeAsync();
}
