using Microsoft.Data.Sqlite;
namespace QueryLens.Core;
public sealed class LocalStore : IAsyncDisposable
{
 readonly string _cs;
 public LocalStore(string path)=>_cs=new SqliteConnectionStringBuilder{DataSource=path,Pooling=false}.ToString();
 SqliteConnection New()=>new(_cs);
 static void Add(SqliteCommand c,string n,object? v)=>c.Parameters.AddWithValue("$"+n,v??DBNull.Value);
 public async Task InitializeAsync(CancellationToken ct=default)
 {
  await using var cn=New(); await cn.OpenAsync(ct);
  await using var tx=(SqliteTransaction)await cn.BeginTransactionAsync(ct);
  await using var c=cn.CreateCommand(); c.Transaction=tx;
  c.CommandText="PRAGMA foreign_keys=ON; CREATE TABLE IF NOT EXISTS connections(id TEXT PRIMARY KEY,name TEXT NOT NULL,dialect TEXT NOT NULL,host TEXT,port INTEGER,database_name TEXT,auth TEXT,use_tls INTEGER,timeout_seconds INTEGER,user_name TEXT,secret_ref TEXT,product_variant TEXT); CREATE TABLE IF NOT EXISTS slow_queries(id TEXT PRIMARY KEY,connection_id TEXT,raw_sql TEXT,redacted_sql TEXT,normalized_sql TEXT,fingerprint TEXT,observed_at TEXT,calls INTEGER,total_ms REAL,min_ms REAL,max_ms REAL,rows_count INTEGER,native_id TEXT,database_name TEXT,is_offline INTEGER,dialect TEXT,semantics TEXT); CREATE TABLE IF NOT EXISTS plans(id TEXT PRIMARY KEY,connection_id TEXT,dialect TEXT,version TEXT,method TEXT,collected_at TEXT,raw_text TEXT,is_baseline INTEGER,fingerprint TEXT,is_offline INTEGER,source_origin TEXT); CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT); PRAGMA user_version=3;";
  await c.ExecuteNonQueryAsync(ct); await tx.CommitAsync(ct);
  // Upgrade databases created by earlier builds without destroying user data.
  await EnsureColumnAsync(cn,"connections","product_variant","TEXT",ct);
  await EnsureColumnAsync(cn,"slow_queries","database_name","TEXT",ct);
  await EnsureColumnAsync(cn,"slow_queries","dialect","TEXT",ct);
  await EnsureColumnAsync(cn,"slow_queries","semantics","TEXT",ct);
  await EnsureColumnAsync(cn,"plans","source_origin","TEXT",ct);
 }
 static async Task EnsureColumnAsync(SqliteConnection cn,string table,string column,string type,CancellationToken ct)
 {
  await using var check=cn.CreateCommand(); check.CommandText=$"SELECT 1 FROM pragma_table_info('{table}') WHERE name=$column LIMIT 1"; Add(check,"column",column);
  if(await check.ExecuteScalarAsync(ct) is not null) return;
  await using var alter=cn.CreateCommand(); alter.CommandText=$"ALTER TABLE {table} ADD COLUMN {column} {type}"; await alter.ExecuteNonQueryAsync(ct);
 }
 public async Task SaveConnectionAsync(ConnectionProfile p,CancellationToken ct=default){await using var cn=New();await cn.OpenAsync(ct);await using var c=cn.CreateCommand();c.CommandText="INSERT OR REPLACE INTO connections VALUES($id,$name,$dialect,$host,$port,$db,$auth,$tls,$timeout,$user,$secret,$variant)";Add(c,"id",p.Id);Add(c,"name",p.Name);Add(c,"dialect",p.Dialect);Add(c,"host",p.Host);Add(c,"port",p.Port);Add(c,"db",p.Database);Add(c,"auth",p.Authentication);Add(c,"tls",p.UseTls?1:0);Add(c,"timeout",p.TimeoutSeconds);Add(c,"user",p.UserName);Add(c,"secret",p.SecretReference is null?null:Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(p.SecretReference)));Add(c,"variant",p.ProductVariant);await c.ExecuteNonQueryAsync(ct);}
 public async Task<IReadOnlyList<ConnectionProfile>> GetConnectionsAsync(CancellationToken ct=default){await using var cn=New();await cn.OpenAsync(ct);await using var c=cn.CreateCommand();c.CommandText="SELECT id,name,dialect,host,port,database_name,auth,use_tls,timeout_seconds,user_name,secret_ref,product_variant FROM connections";await using var r=await c.ExecuteReaderAsync(ct);var l=new List<ConnectionProfile>();while(await r.ReadAsync(ct)){string? s=r.IsDBNull(10)?null:r.GetString(10);if(s!=null){try{s=System.Text.Encoding.UTF8.GetString(Convert.FromBase64String(s));}catch{}}l.Add(new(Guid.Parse(r.GetString(0)),r.GetString(1),Enum.Parse<DatabaseDialect>(r.GetString(2)),r.IsDBNull(3)?"":r.GetString(3),r.IsDBNull(4)?0:r.GetInt32(4),r.IsDBNull(5)?"":r.GetString(5),Enum.Parse<AuthenticationMode>(r.GetString(6)),r.GetInt32(7)!=0,r.GetInt32(8),r.IsDBNull(9)?null:r.GetString(9),s,r.IsDBNull(11)?null:r.GetString(11)));}return l;}
 public async Task SaveSlowQueryAsync(SlowQuery q,CancellationToken ct=default){await using var cn=New();await cn.OpenAsync(ct);await using var c=cn.CreateCommand();c.CommandText="INSERT OR REPLACE INTO slow_queries VALUES($id,$cid,$raw,$red,$norm,$fp,$at,$calls,$total,$min,$max,$rows,$native,$db,$offline,$dialect,$sem)";Add(c,"id",q.Id);Add(c,"cid",q.ConnectionId);Add(c,"raw",q.RawSql);Add(c,"red",q.RedactedSql);Add(c,"norm",q.NormalizedSql);Add(c,"fp",q.Fingerprint);Add(c,"at",q.ObservedAt.ToString("O"));Add(c,"calls",q.Calls);Add(c,"total",q.TotalDuration?.TotalMilliseconds);Add(c,"min",q.MinDuration?.TotalMilliseconds);Add(c,"max",q.MaxDuration?.TotalMilliseconds);Add(c,"rows",q.Rows);Add(c,"native",q.NativeQueryId);Add(c,"db",q.Database);Add(c,"offline",q.IsOfflineSample?1:0);Add(c,"dialect",q.Dialect);Add(c,"sem",q.Semantics);await c.ExecuteNonQueryAsync(ct);}
 public async Task SavePlanAsync(ExecutionPlan p,CancellationToken ct=default){await using var cn=New();await cn.OpenAsync(ct);await using var c=cn.CreateCommand();c.CommandText="INSERT OR REPLACE INTO plans VALUES($id,$cid,$dialect,$version,$method,$at,$raw,$base,$fp,$offline,$origin)";Add(c,"id",p.Id);Add(c,"cid",p.ConnectionId);Add(c,"dialect",p.Dialect);Add(c,"version",p.SourceVersion);Add(c,"method",p.CollectionMethod);Add(c,"at",p.CollectedAt.ToString("O"));Add(c,"raw",p.RawText);Add(c,"base",p.IsBaseline?1:0);Add(c,"fp",p.QueryFingerprint);Add(c,"offline",p.IsOfflineSample?1:0);Add(c,"origin",p.SourceOrigin);await c.ExecuteNonQueryAsync(ct);}
 public async Task DeleteConnectionAsync(Guid id,CancellationToken ct=default){await using var cn=New();await cn.OpenAsync(ct);await using var c=cn.CreateCommand();c.CommandText="DELETE FROM connections WHERE id=$id";Add(c,"id",id);await c.ExecuteNonQueryAsync(ct);}
 public async Task<IReadOnlyList<SlowQuery>> GetSlowQueriesAsync(Guid? connectionId=null,int limit=500,CancellationToken ct=default){await using var cn=New();await cn.OpenAsync(ct);await using var c=cn.CreateCommand();c.CommandText="SELECT id,connection_id,raw_sql,redacted_sql,normalized_sql,fingerprint,observed_at,calls,total_ms,min_ms,max_ms,rows_count,native_id,database_name,is_offline,dialect,semantics FROM slow_queries WHERE ($cid IS NULL OR connection_id=$cid) ORDER BY observed_at DESC LIMIT $limit";Add(c,"cid",connectionId);Add(c,"limit",Math.Clamp(limit,1,10000));await using var r=await c.ExecuteReaderAsync(ct);var l=new List<SlowQuery>();while(await r.ReadAsync(ct))l.Add(new(Guid.Parse(r.GetString(0)),r.IsDBNull(1)?null:Guid.Parse(r.GetString(1)),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),DateTimeOffset.Parse(r.GetString(6)),r.GetInt64(7),r.IsDBNull(8)?null:TimeSpan.FromMilliseconds(r.GetDouble(8)),r.IsDBNull(9)?null:TimeSpan.FromMilliseconds(r.GetDouble(9)),r.IsDBNull(10)?null:TimeSpan.FromMilliseconds(r.GetDouble(10)),r.IsDBNull(11)?null:r.GetInt64(11),r.IsDBNull(12)?null:r.GetString(12),r.IsDBNull(13)?null:r.GetString(13),r.GetInt32(14)!=0,r.IsDBNull(15)?DatabaseDialect.Unknown:Enum.Parse<DatabaseDialect>(r.GetString(15)),r.IsDBNull(16)?SnapshotSemantics.Window:Enum.Parse<SnapshotSemantics>(r.GetString(16))));return l;}
 public async Task<IReadOnlyList<ExecutionPlan>> GetPlansAsync(Guid? connectionId=null,int limit=500,CancellationToken ct=default){await using var cn=New();await cn.OpenAsync(ct);await using var c=cn.CreateCommand();c.CommandText="SELECT id,connection_id,dialect,version,method,collected_at,raw_text,is_baseline,fingerprint,is_offline,source_origin FROM plans WHERE ($cid IS NULL OR connection_id=$cid) ORDER BY collected_at DESC LIMIT $limit";Add(c,"cid",connectionId);Add(c,"limit",Math.Clamp(limit,1,10000));await using var r=await c.ExecuteReaderAsync(ct);var l=new List<ExecutionPlan>();while(await r.ReadAsync(ct)){var d=Enum.Parse<DatabaseDialect>(r.GetString(2));var raw=r.GetString(6);PlanNode root;try{root=r.GetString(4).Contains("XML",StringComparison.OrdinalIgnoreCase)?PlanParser.ParseXml(raw,d,r.GetString(3)).Root:PlanParser.ParseJson(raw,d,r.GetString(3)).Root;}catch{root=new PlanNode("Unknown");}l.Add(new(Guid.Parse(r.GetString(0)),r.IsDBNull(1)?null:Guid.Parse(r.GetString(1)),d,r.GetString(3),r.GetString(4),DateTimeOffset.Parse(r.GetString(5)),raw,root,r.GetInt32(7)!=0,r.IsDBNull(8)?null:r.GetString(8),r.GetInt32(9)!=0,r.IsDBNull(10)?null:r.GetString(10)));}return l;}
 public async Task<string?> GetSettingAsync(string key,string? defaultValue=null,CancellationToken ct=default){await using var cn=New();await cn.OpenAsync(ct);await using var c=cn.CreateCommand();c.CommandText="SELECT value FROM settings WHERE key=$key";Add(c,"key",key);return await c.ExecuteScalarAsync(ct) as string??defaultValue;}
 public async Task SaveSettingAsync(string key,string? value,CancellationToken ct=default){await using var cn=New();await cn.OpenAsync(ct);await using var c=cn.CreateCommand();c.CommandText="INSERT OR REPLACE INTO settings(key,value) VALUES($key,$value)";Add(c,"key",key);Add(c,"value",value);await c.ExecuteNonQueryAsync(ct);}
 public async Task<int> ApplyRetentionAsync(int days,CancellationToken ct=default){if(days<0)throw new ArgumentOutOfRangeException(nameof(days));await using var cn=New();await cn.OpenAsync(ct);await using var tx=(SqliteTransaction)await cn.BeginTransactionAsync(ct);await using var c=cn.CreateCommand();c.Transaction=tx;c.CommandText="DELETE FROM slow_queries WHERE observed_at < $cut";Add(c,"cut",DateTimeOffset.UtcNow.AddDays(-days).ToString("O"));var a=await c.ExecuteNonQueryAsync(ct);c.CommandText="DELETE FROM plans WHERE collected_at < $cut";var b=await c.ExecuteNonQueryAsync(ct);await tx.CommitAsync(ct);return a+b;}
 public ValueTask DisposeAsync()=>ValueTask.CompletedTask;
}
